version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    container_name: new-day-api
    image: new_day/api:0.1.0
    depends_on:
      - redis
    ports:
      - "1323:8080"
    volumes:
      - type: bind
        source: ./src
        target: /go/src/app
    env_file:
      - ./src/.env 
  redis:
    build: 
      context: .
      dockerfile: ./.docker/database/Dockerfile
    container_name: new-day-redis
    image: new_day/redis:0.1.0
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.docker/database:/data

  # mysql:
  #   image: mysql:8
  #   container_name: ai-crestra-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ""
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_DATABASE: "crestra"
  #   ports:
  #     - mode: ingress
  #       target: 3306
  #       published: 13306
  #       protocol: tcp
  #   privileged: true
  #   restart: always
  #   tty: true
  #   volumes:
  #     - type: volume
  #       source: ai-crestra-mysql
  #       target: /var/lib/mysql
  #       volume: {}
  #     - type: bind
  #       source: ./db
  #       target: /docker-entrypoint-initdb.d
  #       bind:
  #         create_host_path: true
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #     start_period: 20s