// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/new-day/controller"
	"github.com/new-day/router"
	"github.com/new-day/usecase"
	"github.com/new-day/env"
	"github.com/new-day/repository/openai"
)

// Injectors from wire.go:

func initializeServer(conf *env.Config) *router.Router {
	engine := setupGinServer()
	client := setupOpenAIClient()
	openAI := openai.NewOpenAIRepository(client)

	params := &usecase.Params{
		OpenAI:        openAI,
		Conf:          conf,
	}
	usecaseUsecase := usecase.NewUsecase(params)

	controllerParams := &controller.Params{
		Usecase: usecaseUsecase,
	}
	controllerController := controller.NewController(controllerParams)
	routerParams := &router.Params{
		Engine:     engine,
		Controller: controllerController,
	}
	routerRouter := router.NewRouter(routerParams)
	return routerRouter
}
